#!/usr/bin/env python2.6
import sys
import optparse

import src.daemon
import src.db_stub
import src.settings

if __name__ == '__main__':
  parser = optparse.OptionParser()
  parser.add_option('--host', dest='host', action='store', default='', help='Hostname to listen on')
  parser.add_option('--port', dest='port', action='store', default=10248, help='Port to run on')
  parser.add_option('--settings', dest='settings', action='store', default='~/.quickopend', help='Settings file to use')
  parser.add_option('--test', dest='test', action='store_true', default=False, help='Adds test hooks')
  (options, args) = parser.parse_args()
  options.port = int(options.port)

  settings = src.settings.Settings(options.settings)
  db_stub = src.db_stub.DBStub(settings)

  daemon = src.daemon.create(db_stub, options.host, options.port, options.test)
  daemon.run()
  sys.exit(0)
