#!/usr/bin/env python
# Copyright 2011 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
import sys
import optparse

import src.settings
import src.db_proxy

def load_settings(options):
  settings = src.settings.Settings(options.settings)
  settings.register('host', str, 'localhost')
  settings.register('port', int, 10248)
  return settings

def open_db(settings,options):
  if not options.host:
    options.host = settings.host
  if not options.port:
    options.port = settings.port
  db = src.db_proxy.DBProxy(options.host, options.port)
  return db

def main():
  parser = optparse.OptionParser()
  parser.add_option('--host', dest='host', action='store', help='Hostname of quickopend server')
  parser.add_option('--port', dest='port', action='store', help='Port for quickopend')
  parser.add_option('--settings', dest='settings', action='store', default='~/.quickopen', help='Settings file to use, ~/.quickopen by default')
  (options, args) = parser.parse_args()
  settings = load_settings(options)
  db = open_db(settings, options)

  # try using gtk
  try:
    import pygtk
    pygtk.require('2.0')
    has_gtk = True
  except ImportError:
    pass
  if has_gtk:
    import src.open_dialog_gtk
    src.open_dialog_gtk.run(settings, db)
    return

  # if that didn't work, try using wx
  import wx
  try:
    import wx
    has_wx = True
  except ImportError:
    pass

  if has_wx:
    raise Exception("WX UI not implemented yet.")

  # give up
  raise Exception("No supported UI detected.")

if __name__ == '__main__':
  main()
  sys.exit(0)
