#!/usr/bin/env python2.6
import logging
import sys
import optparse
import os

import src.daemon
import src.db_stub
import src.settings


def main():
  parser = optparse.OptionParser()
  parser.add_option('--host', dest='host', action='store', help='Hostname to listen on')
  parser.add_option('--port', dest='port', action='store', help='Port to run on')
  parser.add_option('--settings', dest='settings', action='store', default='~/.quickopend', help='Settings file to use')
  parser.add_option('--test', dest='test', action='store_true', default=False, help='Adds test hooks')
  parser.add_option(
      '-v', '--verbose', action='count', default=0,
      help='Increase verbosity level (repeat as needed)')
  (options, args) = parser.parse_args()
  if options.verbose >= 2:
    logging.basicConfig(level=logging.DEBUG)
  elif options.verbose:
    logging.basicConfig(level=logging.INFO)
  else:
    logging.basicConfig(level=logging.WARNING)

  settings_file = os.path.expanduser(options.settings)
  settings = src.settings.Settings(settings_file)
  settings.register('host', str, '')
  settings.register('port', int, 10248)

  if options.port:
    options.port = int(options.port)
  else:
    options.port = settings.port

  if not options.host:
    options.host = settings.host
    
  daemon = src.daemon.create(options.host, options.port, options.test)
  db_stub = src.db_stub.DBStub(settings, daemon)

  daemon.run()

if __name__ == '__main__':
  main()
  sys.exit(0)
