#!/usr/bin/env python
# Copyright 2011 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
import os
import re
import sys
import types
import unittest

def discover():
  if hasattr(unittest.TestLoader, 'discover'):
    return unittest.TestLoader().discover('quickopen')

  # poor mans unittest.discover
  loader = unittest.TestLoader()
  subsuites = []
  
  for (dirpath, dirnames, filenames) in os.walk('quickopen'):
    for filename in [x for x in filenames if re.match('.*_test\.py$', x)]:
      if filename.startswith('.') or filename.startswith('_'):
        continue
      print filename
      fqn = dirpath.replace('/', '.') + '.' + re.match('(.+)\.py$', filename).group(1)
      __import__(fqn)
      suite = loader.loadTestsFromModule(sys.modules[fqn])
      subsuites.append(suite)
  return unittest.TestSuite(subsuites)

if __name__ == "__main__":
  # make sure cwd is the base quickopen directory!
  os.chdir(os.path.dirname(__file__))

  suites = discover()
  r = unittest.TextTestRunner()
  r.run(suites)
